#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar  2 10:29:53 2018

@author: valen
"""

import csv

def openFile(fileName, mode):
    try:
        f = open(fileName, mode)
        reader = csv.reader(f)
        return reader
        f.close()
    except:
        print("Coud not open the file {} with mode {}.".format(fileName, mode))
        
def main():
    top5directorsDic = {}
    
    
    directorsDict = {}    
    reader3 = openFile("imdb-top-casts.csv", "r")
    for row in reader3:
        directorsDict[(row[0],row[1])] = row[2:]
    
    countTop5 = 5
    type(top5directorsDic)
    reader = openFile("imdb-top-rated.csv", "r")
    for row in reader:
        try:
            int(row[0])
            if((directorsDict[(row[1],row[2])][0]) in top5directorsDic):
                top5directorsDic[directorsDict[(row[1],row[2])][0]] +=1
            else:
                top5directorsDic[(directorsDict[(row[1],row[2])][0])] =1
            
            
        except:
            continue


    print(top5directorsDic)
    """
    for k,v in top5directorsDic:
        print(k, v)
    """
    #print(directorsDict[('Papillon', '1973')][5]) 
    print(directorsDict[('Papillon', '1973')][0]) 
    print(directorsDict[('101 Dalmatians', '1961')][0])
    #print(directorsDict)
 
    
    reader2 = openFile("imdb-top-grossing.csv", "r")
    for row in reader2:
        if(countTop5 >=0):
           #print(row + ["=====> ", countTop5]) 
           countTop5 -= 1
        else:
            countTop5 = 5
            break
    

main()
